/** @type {import('tailwindcss').Config} */
export default {
  content: [ "./index.html", "./src/**/*.{js,ts,jsx,tsx}" ],
  theme: {
    extend: {
      colors: {
        bg: '#0B1220',
        surface: '#111827',
        elevated: '#1A2438',
        primary: '#356DFF',
        'primary-hover': '#2554CC',
        'primary-glow': 'rgba(53, 109, 255, 0.25)',
        success: '#22C55E',
        warning: '#FACC15',
        danger: '#EF4444',
        info: '#3B82F6',
        'text-main': '#F9FAFB',
        'text-muted': '#9CA3AF',
        'text-dim': '#6B7280',
        'border-main': '#1F2937',
      },
      borderRadius: {
        btn: '10px',
        card: '18px',
        dialog: '20px',
        input: '10px',
        badge: '999px',
        '2xl': '16px',
        '3xl': '24px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        display: ['2.75rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        h1: ['2.25rem', { lineHeight: '1.2' }],
        h2: ['1.875rem', { lineHeight: '1.3' }],
        h3: ['1.5rem', { lineHeight: '1.4' }],
        title: ['1.25rem', { lineHeight: '1.5' }],
        body: ['1rem', { lineHeight: '1.5' }],
        small: ['0.875rem', { lineHeight: '1.5' }],
        caption: ['0.75rem', { lineHeight: '1.5' }],
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '6': '24px',
        '8': '32px',
        '12': '48px',
        '16': '64px',
        '18': '4.5rem',
        '88': '22rem',
        '112': '28rem',
      },
      boxShadow: {
        'level-1': '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.06)',
        'level-2': '0 4px 12px rgba(0, 0, 0, 0.15), 0 2px 4px rgba(0, 0, 0, 0.08)',
        'level-3': '0 12px 40px rgba(0, 0, 0, 0.25), 0 4px 12px rgba(0, 0, 0, 0.12)',
        soft: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
      },
      transitionDuration: {
        fast: '120ms',
        normal: '200ms',
        complex: '300ms',
        max: '400ms',
      },
      transitionTimingFunction: {
        'out': 'cubic-bezier(0, 0, 0.2, 1)',
        'in': 'cubic-bezier(0.4, 0, 1, 1)',
        'panel': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-out': {
          from: { opacity: '1', transform: 'translateY(0)' },
          to: { opacity: '0', transform: 'translateY(8px)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.98)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-right': {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        'slide-out-right': {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(100%)' },
        },
        'toast-in': {
          from: { opacity: '0', transform: 'translateX(100%) translateY(0)' },
          to: { opacity: '1', transform: 'translateX(0) translateY(0)' },
        },
        'toast-out': {
          from: { opacity: '1', transform: 'translateX(0) translateY(0)' },
          to: { opacity: '0', transform: 'translateX(100%) translateY(0)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'progress-fill': {
          from: { width: '0%' },
          to: { width: 'var(--progress-width)' },
        },
        'chevron-rotate': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(180deg)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 200ms ease-out',
        'fade-out': 'fade-out 200ms ease-in',
        'scale-in': 'scale-in 200ms ease-out',
        'slide-in-right': 'slide-in-right 300ms cubic-bezier(0.2, 0.8, 0.2, 1)',
        'slide-out-right': 'slide-out-right 200ms ease-in',
        'toast-in': 'toast-in 300ms ease-out',
        'toast-out': 'toast-out 200ms ease-in forwards',
        'shimmer': 'shimmer 2s ease-in-out infinite',
        'progress': 'progress-fill 400ms ease-out forwards',
      },
    },
  },
  plugins: [],
}